### ISSUE TITLE
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

### ISSUE THREAD

**Issue by hongbepoz** [Adyen/adyen-react-native#107]
**Describe the bug**
I got this error on android

```bash
FATAL EXCEPTION: main
                                                                                                    android.view.InflateException: Binary XML file line #67 in applicationId:layout/fragment_card_component: Binary XML file line #67 in applicationId:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #67 in applicationId:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
                                                                                                    	at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
                                                                                                    	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8855)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #25 in applicationId:layout/card_view: Binary XML file line #25 in applicationId:layout/card_view: Error inflating class com.google.android.material.textfield.TextInputLayout
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #25 in applicationId:layout/card_view: Error inflating class com.google.android.material.textfield.TextInputLayout
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
2022-12-20 12:21:20.027  3714-3714  AndroidRuntime          applicationId                     E  	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                                                                                    	at com.adyen.checkout.card.databinding.CardViewBinding.inflate(CardViewBinding.java:169)
                                                                                                    	at com.adyen.checkout.card.CardView.<init>(CardView.kt:58)
                                                                                                    	at com.adyen.checkout.card.CardView.<init>(CardView.kt:47)
                                                                                                    	at com.adyen.checkout.card.CardView.<init>(Unknown Source:11)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
                                                                                                    	at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
                                                                                                    	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8855)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:241)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:113)
                                                                                                    	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:474)
                                                                                                    	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:433)
                                                                                                    	... 46 more
```

**To Reproduce**
1. Open Drop In
2. Click on `Payment Method` or Select the existing Card
3. See error

**Expected behavior**
Show the card input form or executes the transaction.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 12
 - React Native `"react-native": "0.67.5"`

**Comment by descorp** [comment]
Hey @hongbepoz 

What Theme are you using?

**Comment by hongbepoz** [comment]
> What Theme are you using?

HI @descorp 

I just use `AdyenDropIn.open(paymentMethods, configuration)`.

**Comment by descorp** [comment]
Sorry @hongbepoz

I wasn't clear in my question:
As the error states, our Drop-in expects MaterialComponents scheme. 

```
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
```

In your `styles.xml` what Theme are you using?

**Comment by hongbepoz** [comment]
@descorp 
I use `Theme.AppCompat`. After change to `Theme.MaterialComponents` it work.
Thank you.

**Comment by descorp** [comment]
This was fixed on [beta-9](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.9).
Setting `Theme.MaterialComponents` is no longer needed.

**Comment by RyanLinXiang** [comment]
@descorp Is there a way to NOT use `Theme.MaterialComponents` as this causes conflict with a different package. AdyenAction.handle crashes without using Theme.MaterialComponents #446

**Comment by descorp** [comment]
Hey @RyanLinXiang 

Could you try `Theme.MaterialComponents.**.Bridge` instead?

**Comment by RyanLinXiang** [comment]
@descorp Yes! Working. Maybe adding this to the documentation? 😃

**Comment by descorp** [comment]
Good idea!
Thanks for checking!
