### ISSUE TITLE
Can't see a payment sheet for "card" on Android

### ISSUE THREAD

**Issue by iszhuravlev** [Adyen/adyen-react-native#115]
**Describe the bug**
Hi, maybe it'll turn into a `question`, but let me just describe the issue I'm facing:
When I press "Pay with Card" in a dropIn, the `onSubmit` callback gets fired immediately.

As far as I understood from [this docs page](https://docs.adyen.com/online-payments/web-drop-in/additional-use-cases/advanced-flow#step-2-add-drop-in) (point 6), `onSubmit` has to return me encoded card details, from which I make the conclusion, that something's wrong, because for that to happen I must see the payment sheet (to enter card details) first.

**To Reproduce**
1. Open the drop-in
2. Click on "Pay with card"
3. See "onSubmit" getting called

**Expected behavior**
The form with card details inputs shown first; when I enter details and press "Pay" - onSubmit should be fired.

**Device**
 - Model: Emulator Pixel 3a API 32
 - OS: Android 12

**Comment by descorp** [comment]
Hey @iszhuravlev 

When this happens, what `paymentMethod.type` you see in `onSubmit` data?

**Comment by iszhuravlev** [comment]
@descorp it's `card`:
```
"paymentMethod": {
    "type": "card"
  }
```
I tried with `scheme` but the app crashes then.

**Comment by descorp** [comment]
Hey @iszhuravlev 

Are you hardcoding `paymentMethods` JSON?

On DropIn it supposed to be `scheme`, otherwise it fallbacks to "instant payment" and triggers `onSubmit`.

> I tried with scheme but the app crashes then.

Can you share crash logs?

**Comment by iszhuravlev** [comment]
@descorp No, I substituted `scheme` with `card` because it worked on iOS and because we needed it to be card for consistency, but I can't revert this piece of code - that's not a problem.

Logcat says:
```
01-05 15:04:15.308  6098  6098 D CO.PaymentMethodListDialogFragmentKt: onPaymentMethodSelected - scheme
01-05 15:04:15.308  6098  6098 D CO.PaymentMethodListDialogFragmentKt: onPaymentMethodSelected: payment method is supported
01-05 15:04:15.308  6098  6098 D CO.DropInActivityKt: showComponentDialog
01-05 15:04:15.336  6098  6285 D EGL_emulation: app_time_stats: avg=330.57ms min=2.67ms max=3256.84ms count=10
01-05 15:04:15.336  6098  6285 D OpenGLRenderer: endAllActiveAnimators on 0xb4000079c0779df0 (RippleDrawable) with handle 0xb4000078d06aa030
01-05 15:04:15.338   634  1912 W InputManager-JNI: Input channel object '3cd3b4f com.getarive.app/com.adyen.checkout.dropin.ui.DropInActivity (client)' was disposed without first being removed with the input manager!
01-05 15:04:15.344   634   653 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
01-05 15:04:15.358  6098  6098 D CO.PublicKeyRepositoryKt: fetching publicKey from API
01-05 15:04:15.375  6098  6098 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-05 15:04:15.379  6098  6098 E AndroidRuntime: FATAL EXCEPTION: main
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Process: com.getarive.app, PID: 6098
01-05 15:04:15.379  6098  6098 E AndroidRuntime: android.view.InflateException: Binary XML file line #67 in com.getarive.app:layout/fragment_card_component: Binary XML file line #67 in com.getarive.app:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #67 in com.getarive.app:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in com.getarive.app:layout/card_view: Binary XML file line #25 in com.getarive.app:layout/card_view: Error inflating class com.google.android.material.textfield.TextInputLayout
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in com.getarive.app:layout/card_view: Error inflating class com.google.android.material.textfield.TextInputLayout
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.card.databinding.CardViewBinding.inflate(CardViewBinding.java:169)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.card.CardView.<init>(CardView.kt:58)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.card.CardView.<init>(CardView.kt:47)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.card.CardView.<init>(Unknown Source:11)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-05 15:04:15.379  6098  6098 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:241)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:113)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:474)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:433)
01-05 15:04:15.379  6098  6098 E AndroidRuntime:        ... 46 more
01-05 15:04:15.393   634  6667 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-05 15:04:15.409   634   662 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-05 15:04:15.409   634   662 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-05 15:04:15.421   634  1912 W ActivityTaskManager:   Force finishing activity com.getarive.app/com.adyen.checkout.dropin.ui.DropInActivity
01-05 15:04:15.428   465   561 D PermissionCache: checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (278 us)
01-05 15:04:15.428   435   435 D goldfish-address-space: claimShared: Ask to claim region [0x1f4a78000 0x1f5054000]
01-05 15:04:15.438   202   202 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@4.0::IMapper/default in either framework or device VINTF manifest.
01-05 15:04:15.438   634  1682 I Gralloc4: mapper 4.x is not supported
01-05 15:04:15.442   634  1682 D HostConnection: createUnique: call
01-05 15:04:15.443   634  1682 D HostConnection: HostConnection::get() New Host Connection established 0xb4000079404b6a90, tid 1682
01-05 15:04:15.443   634  1682 D goldfish-address-space: allocate: Ask for block of size 0x100
01-05 15:04:15.443   634  1682 D goldfish-address-space: allocate: ioctl allocate returned offset 0x1f3ff8000 size 0x8000
01-05 15:04:15.446   634  1682 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
01-05 15:04:15.456   634  1912 W ActivityTaskManager:   Force finishing activity com.getarive.app/.MainActivity
```

**Comment by descorp** [comment]
This is recurring problem. We'll update README!
You can find fix [here](https://github.com/Adyen/adyen-react-native/issues/107)

Thanks for feedback!

**Comment by iszhuravlev** [comment]
@descorp Brilliant, thank you, it worked!
