### ISSUE TITLE
Android: App crashes whenever redirecting (e.g. to PayPal)

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#199]
**Describe the bug**
In Android the app crashes whenever nativeComponent.handle() is called to handle redirect (e.g. PayPal).

**Smartphone (please complete the following information):**
 - Device: Pixel XL API 33, Android Emulator, Version Tiramisu
 - OS: MacBook Pro M1

**Error log**
2023-04-27 01:50:30.277 11317-11317/*.**.**app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: *.**.**app, PID: 11317
    java.lang.NoSuchMethodError: No virtual method setDefaultColorSchemeParams(Landroidx/browser/customtabs/CustomTabColorSchemeParams;)Landroidx/browser/customtabs/CustomTabsIntent$Builder; in class Landroidx/browser/customtabs/CustomTabsIntent$Builder; or its super classes (declaration of 'androidx.browser.customtabs.CustomTabsIntent$Builder' appears in /data/app/~~9UvaD_8JVVP_mGLBatSGCA==/*.**.**ap-qkU8xjKJ6YR0nXmHu5c05w==/base.apk)
        at com.adyen.checkout.redirect.RedirectUtil.createCustomTabIntent(RedirectUtil.kt:129)
        at com.adyen.checkout.redirect.RedirectUtil.createRedirectIntent(RedirectUtil.kt:112)
        at com.adyen.checkout.redirect.RedirectDelegate.makeRedirect(RedirectDelegate.kt:36)
        at com.adyen.checkout.redirect.RedirectDelegate.makeRedirect(RedirectDelegate.kt:23)
        at com.adyen.checkout.redirect.RedirectComponent.handleActionInternal(RedirectComponent.java:63)
        at com.adyen.checkout.components.base.BaseActionComponent.handleAction(BaseActionComponent.java:56)
        at com.adyen.checkout.dropin.ActionHandler.handleAction(ActionHandler.kt:78)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleAction(DropInActivity.kt:493)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleDropInServiceResult(DropInActivity.kt:458)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleDropInServiceResult(DropInActivity.kt:448)
        at com.adyen.checkout.dropin.ui.DropInActivity.access$handleDropInServiceResult(DropInActivity.kt:90)
        at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1$1.invoke(DropInActivity.kt:116)
        at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1$1.invoke(DropInActivity.kt:116)
        at com.adyen.checkout.dropin.service.DropInService$observeResult$2.emit(DropInService.kt:467)
        at com.adyen.checkout.dropin.service.DropInService$observeResult$2.emit(DropInService.kt:467)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
        at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:908)
        at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
        at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:134)
        at com.adyen.checkout.dropin.service.DropInService$sendResult$1.invokeSuspend(DropInService.kt:221)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ad135f, Dispatchers.Main.immediate]

**Comment by RyanLinXiang** [comment]
Dear all,

we fixed the issue, never mind. Our androidx browser version is different from what Adyen requires:

```
	configurations.all {
		resolutionStrategy {
			force 'androidx.browser:browser:1.2.0'
		}
```

Change to `androidx.browser:browser:1.4.0` worked!

**Comment by descorp** [comment]
Hey @RyanLinXiang 

FYI, Our Android SDK uses [1.3.0](https://github.com/Adyen/adyen-android/blob/4.11.0/build.gradle#L63)

---

Could you also answer your own [Stackoverflow](https://stackoverflow.com/questions/76119569/react-native-android-no-virtual-method-setdefaultcolorschemeparams) question? :)

**Comment by RyanLinXiang** [comment]
Done! :)
